### ISSUE TITLE
Propose add WriteMultipleCoils() Method feature to ModbusClientBase.cs

### ISSUE THREAD

**Issue by PRIMETSS** [WildernessLabs/Meadow.Modbus#26]
Library has WriteCoil() [Single coil] but no ability to write to multiple coils.
`WriteCoil(byte modbusAddress, ushort register, bool value)`

If needing to change state of multiple coils currently have to issue multiple Modbus packet writes. This adds significant bandwidth overhead if setting >4 coils! This can causes significate polling issues on low speed or high traffic buses.

Propose adding this feature, have written and tested a working example and physically tested against hardware

[Example Repo Here](https://github.com/PRIMETSS/Meadow.Modbus/blob/PTSSLocalDev-Add-WriteMultipleCoils/src/Meadow.Modbus/Clients/ModbusClientBase.cs#L246)

This is a custom forked repo which has not been kept up-to-date with main repo at moment.

**Comment by ctacke** [comment]
Yes, you can definitely see what functions I've been using based on what I implement.  I believe you PRed multiple coil support earlier, and I cherry-picked it in, as there's definitely an implementation here:

https://github.com/WildernessLabs/Meadow.Modbus/blob/81441829ef1a92a35d5035acf5882f324972c12e/src/Meadow.Modbus/Clients/ModbusClientBase.cs#L248

If this doesn't work, let me know

**Comment by PRIMETSS** [comment]
Apologies I was stuck on using a older Forked version that was working with project.
Have tested with 1.8.0.1 and yes it is there/working, Thankyou!

[Closing]
