### ISSUE TITLE
Error when calling WriteCoil() to a physical RS485 device

### ISSUE THREAD

**Issue by PRIMETSS** [WildernessLabs/Meadow.Modbus#6]
I cannot use WriteCoil() to a physical RS485 device I have here on bench [](https://www.ebyte.com/en/downpdf.aspx?id=1642) without receiving a CRC checksum exception `Meadow.Modbus.CrcException: 'CRC Failure'`

Wondering if the devices firmware is incorrectly handling CRC building I checked the devices raw Requests & Response messages with several tools including [](https://rapidscada.net/modbus/) which has a handy feature to decode the message structure.
I used an example Request show in the manual to send the turn on a coil request `01 05 00 00 FF FF 8C 3A` it shows CRC error.
ReadRegister() works fine!

After checking the specs for RS485 RTU client constructing CRC's for writing to a coil it appears the correct format for the data is 0xFF00 not 0xFFFF []
[https://www.fernhillsoftware.com/help/drivers/modbus/modbus-protocol.html](https://www.fernhillsoftware.com/help/drivers/modbus/modbus-protocol.html#readInputRegs:~:text=Coil%20value-,0x0000%20or%200xFF00,-If%20the%20PLC)
(https://www.modbustools.com/modbus.html#function05:~:text=Function%2005%20(05hex,affect%20the%20coil.)

![image](https://user-images.githubusercontent.com/11331370/236659314-36da959d-cc49-4818-8d63-474206ddb35c.png)
![image](https://user-images.githubusercontent.com/11331370/236659337-2d9f909f-c9f6-4a56-bb57-59a95180f3ed.png)

[](https://github.com/WildernessLabs/Meadow.Modbus/blob/main/src/Meadow.Modbus/Clients/ModbusClientBase.cs#:~:text=var%20data%20%3D%20value%20%3F%20new%20byte%5B%5D%20%7B%200xff%2C%200xff%20%7D%20%3A%20new%20byte%5B%5D%20%7B%200x00%2C%200x00%20%7D%3B)

I'm having issues building LIB from any branch @ repo (`'SerialPortShim' does not implement interface member 'ISerialPort.DataBits.set'	Meadow.Modbus` to do a pull request at this time.
`

Thoughts anyone? Is the device correct or this code?
Might have Pull Request by tomorrow, just testing now.

PR: [https://github.com/WildernessLabs/Meadow.Modbus/pull/12#issue-1701227438](https://github.com/WildernessLabs/Meadow.Modbus/pull/12#issue-1701227438)

**Comment by ctacke** [comment]
Issue fixed in the next release (which will include RTU server support)
